FROM narumi/base

LABEL maintainer="Narumi"

RUN pip3 install -U pip &&\
    pip3 install -U numpy \
                    scipy \
                    matplotlib \
                    jupyter &&\
    rm -rf ~/.cache/pip


